# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LXCoach' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LXCoach
  
  pod 'AFNetworking', '~> 3.2.1'
  pod 'YYModel', '~> 1.0.4'
  pod 'YYCache', '~> 1.0.4'
  pod 'YYCategories', '~> 1.0.4'
  pod 'VTMagic'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'SDWebImage', '~> 4.3.3'
  pod 'SDWebImage/GIF', '~> 4.3.3'
  pod 'QQ_XGPush'
  pod 'Masonry'
  pod 'IQKeyboardManager'
end
